#!/usr/bin/env python3
"""Generate deterministic configs for the direct system-TUN benchmark."""

from pathlib import Path


NODES = {
    "a": {
        "nsec": "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
        "npub": "npub1sjlh2c3x9w7kjsqg2ay080n2lff2uvt325vpan33ke34rn8l5jcqawh57m",
        "peer": "b",
        "peer_ip": "172.31.30.11",
    },
    "b": {
        "nsec": "b102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1fb0",
        "npub": "npub1tdwa4vjrjl33pcjdpf2t4p027nl86xrx24g4d3avg4vwvayr3g8qhd84le",
        "peer": "a",
        "peer_ip": "172.31.30.10",
    },
}


def render(node_id: str) -> str:
    node = NODES[node_id]
    peer_id = node["peer"]
    peer = NODES[peer_id]
    return f'''# Generated by testing/tun-performance/generate-configs.py.
node:
  identity:
    nsec: "{node["nsec"]}"

tun:
  enabled: true
  name: fips0
  mtu: 1280

dns:
  enabled: true

transports:
  udp:
    bind_addr: "0.0.0.0:2121"
    mtu: 1472
    recv_buf_size: 16777216
    send_buf_size: 16777216

peers:
  - npub: "{peer["npub"]}"
    alias: "node-{peer_id}"
    addresses:
      - transport: udp
        addr: "{node["peer_ip"]}:2121"
    connect_policy: auto_connect
'''


def main() -> None:
    output = Path(__file__).resolve().parent / "generated-configs"
    output.mkdir(parents=True, exist_ok=True)
    for node_id in NODES:
        (output / f"node-{node_id}.yaml").write_text(render(node_id))
    env = "\n".join(f"NPUB_{node_id.upper()}={node['npub']}" for node_id, node in NODES.items())
    (output / "npubs.env").write_text(env + "\n")


if __name__ == "__main__":
    main()
