#!/usr/bin/env python3
"""Generate the fixed, deterministic A--B--C forwarding lab configs."""

from pathlib import Path


NODES = {
    "a": {
        "nsec": "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
        "npub": "npub1sjlh2c3x9w7kjsqg2ay080n2lff2uvt325vpan33ke34rn8l5jcqawh57m",
        "peers": [("b", "172.31.10.11")],
    },
    "b": {
        "nsec": "b102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1fb0",
        "npub": "npub1tdwa4vjrjl33pcjdpf2t4p027nl86xrx24g4d3avg4vwvayr3g8qhd84le",
        "peers": [("a", "172.31.10.10"), ("c", "172.31.20.12")],
    },
    "c": {
        "nsec": "c102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1fc0",
        "npub": "npub1cld9yay0u24davpu6c35l4vldrhzvaq66pcqtg9a0j2cnjrn9rtsxx2pe6",
        "peers": [("b", "172.31.20.11")],
    },
}


def render(node_id: str) -> str:
    node = NODES[node_id]
    peers = []
    for peer_id, address in node["peers"]:
        peer = NODES[peer_id]
        peers.append(
            f'''  - npub: "{peer["npub"]}"
    alias: "node-{peer_id}"
    addresses:
      - transport: udp
        addr: "{address}:2121"
    connect_policy: auto_connect'''
        )
    dns_enabled = "false" if node_id == "b" else "true"
    tun_enabled = "false" if node_id == "b" else "true"
    return f'''# Generated by testing/forwarding/generate-configs.py.
node:
  identity:
    nsec: "{node["nsec"]}"

tun:
  enabled: {tun_enabled}
  name: fips0

dns:
  enabled: {dns_enabled}

transports:
  udp:
    bind_addr: "0.0.0.0:2121"
    mtu: 1472
    recv_buf_size: 16777216
    send_buf_size: 16777216

peers:
{chr(10).join(peers)}
'''


def main() -> None:
    output = Path(__file__).resolve().parent / "generated-configs"
    output.mkdir(parents=True, exist_ok=True)
    for node_id in NODES:
        (output / f"node-{node_id}.yaml").write_text(render(node_id))
    env = "\n".join(f"NPUB_{node_id.upper()}={node['npub']}" for node_id, node in NODES.items())
    (output / "npubs.env").write_text(env + "\n")


if __name__ == "__main__":
    main()
