#!/usr/bin/env bash
# Run the deterministic FIPS dataplane safety tests inside a Linux container.
#
# Useful from local macOS hosts: local `cargo test` exercises Darwin cfg paths,
# while this covers Linux-only fair-worker queue behavior without needing a
# separate host checkout.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE="${FIPS_LINUX_TEST_IMAGE:-rust:1.93-bookworm}"
TARGET_VOLUME="${FIPS_LINUX_TEST_TARGET_VOLUME:-fips-dataplane-safety-target}"
REGISTRY_VOLUME="${FIPS_LINUX_TEST_REGISTRY_VOLUME:-fips-dataplane-safety-registry}"
GIT_VOLUME="${FIPS_LINUX_TEST_GIT_VOLUME:-fips-dataplane-safety-git}"
RUSTUP_VOLUME="${FIPS_LINUX_TEST_RUSTUP_VOLUME:-fips-dataplane-safety-rustup}"

DEFAULT_FILTERS=(
  encrypt_worker_lane_policy_keeps_endpoint_bulk_explicit
  encrypt_worker_shard_owns_batch_drain_and_flush_error
  queued_fmp_send_job_owns_lane_and_target_key
  queued_target_key_survives_seal_and_batch_grouping
  sealed_send_packet_owns_target_wire_and_drop_policy
  single_flow_full_backpressures_instead_of_dropping
  tight_bulk_cap_limits_single_flow_to_fast_lane_plus_fair_budget
  new_flow_can_enter_when_hot_flow_reaches_per_flow_cap
  hot_flow_backpressures_when_others_are_waiting
  send_backpressure
  pipelined_endpoint_wire_uses_reserved_counters_and_offsets
  test_pipelined_send_counter_reservation_is_single_owner
  priority_flow_enters_when_bulk_flow_reaches_per_flow_cap
  priority_flow_enters_when_bulk_worker_queue_is_full
  priority_reserve_does_not_shrink_with_tight_bulk_channel_cap
  fair_admission_keys_pressure_by_exact_send_target
  fair_admission_reservation_owns_release_key
  queued_fmp_send_job_owns_clamped_scheduling_weight
  selected_send_target_key_drives_dispatch_and_admission_without_endpoint_flow
  endpoint_flow_key_splits_admission_within_one_send_target
  selected_send_batch_owns_target_fifo_and_drop_policy
  linux_send_batch_attempt_owns_cursor_and_backpressure_policy
  encrypt_worker_dispatch_preserves_single_flow_worker_and_fifo_order
  fair_dispatch_does_not_block_rx_loop_on_full_bulk_queue
  fmp_worker_send_reservation_owns_counter_header_and_cipher
  fmp_worker_target_fallback_consumes_one_inline_counter
  decrypt_worker_channel_cap_prefers_specific_then_shared_value
  decrypt_fallback_bulk_cap_ignores_shared_worker_cap
  decrypt_worker_priority_packet_classifier_keeps_small_packets_reserved
  decrypt_job_owns_lane_selected_at_construction
  decrypt_fallback_event_owns_lane_selected_at_construction
  decrypt_worker_full_queue_drops_bulk_without_waiting
  decrypt_worker_priority_packet_uses_priority_lane_when_bulk_queue_is_full
  decrypt_worker_register_uses_priority_lane_when_bulk_queue_is_full
  decrypt_worker_register_full_returns_false_without_waiting
  decrypt_worker_drain_registers_priority_before_bulk_jobs
  decrypt_worker_drain_unregisters_priority_before_bulk_jobs
  decrypt_worker_accepts_fmp_replay_only_after_aead_success
  owned_session_state_open_fmp_owns_replay_acceptance
  open_fsp_established_frame_failed_all_epochs_does_not_consume_replay
  reserve_fsp_worker_send_owns_counter_header_and_cipher
  decrypt_worker_shard_owns_register_and_unregister_state
  decrypt_session_key_routes_registration_jobs_and_unregister_to_same_worker
  decrypt_worker_unregister_uses_priority_lane_when_bulk_queue_is_full
  decrypt_worker_unregister_full_returns_false_without_waiting
  decrypt_worker_fallback_event_classifier_uses_priority_and_bulk_lanes
  decrypt_worker_fallback_bulk_full_does_not_starve_priority_events
  decrypt_worker_fallback_priority_full_returns_false_without_waiting
  fallback_drain_prefers_ready_priority_over_selected_bulk
  rx_loop_data_drain_stats_owns_counts_total_and_pressure
  rx_loop_maintenance_state_owns_activity_window_and_timeout_skip
  rx_loop_maintenance_plan_owns_pressure_skip_and_timeout_budget
  endpoint_command_owns_lane_selected_at_construction
  endpoint_send_command_owns_payload_lane_and_queue_stamp
  endpoint_data_payload_owns_drop_policy_selected_at_construction
  endpoint_data_send_owns_remote_identity_and_payload_policy
  pending_endpoint_data_queue_owns_drop_oldest_policy
  pending_tun_packet_queue_owns_drop_oldest_policy
  pending_session_traffic_queues_own_destination_admission
  pending_discovery_lookup_queue_owns_dedup_and_capacity
  recent_discovery_requests_own_reverse_path_dedup_capacity_and_expiry
  pending_route_retries_own_expiry_due_order_and_budgets
  local_send_failures_own_peer_scoped_fast_dead_clear_and_expiry
  session_direct_degradation_owns_hold_extension_expiry_and_clear
  discovery_fallback_transit_owns_target_exception_block_and_bootstrap_policy
  bootstrap_transports_own_membership_peer_npub_and_cleanup
  transport_drop_tracker_owns_rising_edge_state_and_cleanup
  pending_outbound_handshakes_own_msg2_index_matching_and_cleanup
  link_address_index_owns_lookup_replace_and_stale_safe_remove
  link_registry_owns_storage_address_index_and_stale_safe_cleanup
  session_index_registry_owns_lookup_replace_remove_and_peer_membership
  peer_lifecycle_registry_owns_session_index_removal_and_remaining_owner_state
  peer_lifecycle_registry_owns_active_peer_insert_and_current_session_index
  peer_lifecycle_registry_owns_current_session_index_repair
  peer_lifecycle_registry_owns_current_session_replacement_and_index_handoff
  peer_lifecycle_registry_owns_pending_rekey_session_and_index_registration
  peer_lifecycle_registry_owns_authenticated_fmp_receive_bookkeeping
  peer_lifecycle_registry_owns_fmp_send_bookkeeping
  peer_lifecycle_registry_owns_fmp_send_preparation_and_seal_paths
  peer_lifecycle_registry_owns_connected_udp_activation_plan
  peer_lifecycle_registry_owns_connected_udp_install_and_clear
  peer_lifecycle_registry_owns_link_dead_direct_path_degradation
  peer_lifecycle_registry_owns_active_peer_teardown_session_indices
  session_registry_owns_fsp_send_bookkeeping
  session_registry_owns_endpoint_session_storage_and_worker_registration_mirror
  decrypt_session_registrations_own_worker_acceptance_and_unregister_gate
  identity_cache_owns_prefix_validation_lru_touch_and_lookup_views
  configured_peer_send_weights_own_identity_parse_and_default_policy
  learned_route_fallback_exploration_owns_interval_dedup_and_expiry
  packet_drain_cursor_owns_first_packet_budget_and_interleave
  priority_bulk_drain_cursor_owns_selected_head_and_budget
  tun_outbound_drain_cursor_owns_first_packet_and_budget
  worker_preserves_fmp_flags_through_fallback
  worker_reports_fmp_aead_failure_to_rx_loop
  pending_session_queues_drop_oldest_per_destination
  pending_session_queues_reject_new_destinations_at_cap
  endpoint_command_tx_helper_classifies_priority_and_bulk_payloads
  endpoint_payload_traffic_classifier_prioritizes_control_sized_packets
  endpoint_payload_traffic_classifier_prioritizes_ipv4_icmp_ping
  endpoint_flow_dispatch_key_tracks_inner_ip_transport_flow
  test_reply_learned_prefers_live_mesh_route_over_stale_direct_peer
  test_reply_learned_prefers_live_mesh_route_over_session_degraded_direct_peer
  test_reply_learned_keeps_configured_static_direct_peer_despite_session_degraded
  test_reply_learned_keeps_configured_static_direct_peer_over_lower_cost_fallback
  test_tree_routing_skips_session_degraded_direct_peer_for_payload
  test_stale_session_receiver_reports_do_not_change_route_choice
  test_stale_mmp_receiver_reports_do_not_change_route_choice
  test_session_receiver_loss_degrades_direct_and_uses_fallback
  fresh_control_with_unreturned_endpoint_data_blocks_direct_without_known_fallback
  test_fresh_bogus_session_metrics_without_valid_rtt_do_not_change_route_choice
  test_ignores_duplicate_receiver_report_after_valid_sample
  test_ignores_out_of_order_receiver_report_after_valid_sample
  test_parent_reeval_ignores_unmeasured_peer_costs
  test_parent_reeval_ignores_fresh_bogus_metrics_without_valid_rtt
  connected_udp
)

if [[ "$#" -gt 0 ]]; then
  FILTERS=("$@")
else
  FILTERS=("${DEFAULT_FILTERS[@]}")
fi

docker run --rm \
  -v "$ROOT_DIR:/workspace:ro" \
  -v "$TARGET_VOLUME:/cargo-target" \
  -v "$REGISTRY_VOLUME:/usr/local/cargo/registry" \
  -v "$GIT_VOLUME:/usr/local/cargo/git" \
  -v "$RUSTUP_VOLUME:/usr/local/rustup" \
  -w /workspace \
  "$IMAGE" \
  bash -euo pipefail -c '
    export DEBIAN_FRONTEND=noninteractive
    if ! dpkg -s libdbus-1-dev libclang-dev pkg-config >/dev/null 2>&1; then
      apt-get update >/dev/null
      apt-get install -y --no-install-recommends libdbus-1-dev libclang-dev pkg-config >/dev/null
      rm -rf /var/lib/apt/lists/*
    fi
    export CARGO_TARGET_DIR=/cargo-target
    for filter in "$@"; do
      echo "--- cargo test -p fips-core ${filter} ---"
      cargo test -p fips-core "$filter"
    done
  ' bash "${FILTERS[@]}"
